'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace E2636


	Partial Public Class [Default]

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' GlobalEvents control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GlobalEvents As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

		''' <summary>
		''' SourceGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SourceGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' SourceDS control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SourceDS As Global.System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' btnMoveSelectedItemsToRight control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnMoveSelectedItemsToRight As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' btnMoveAllItemsToRight control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnMoveAllItemsToRight As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' btnMoveSelectedItemsToLeft control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnMoveSelectedItemsToLeft As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' btnMoveAllItemsToLeft control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnMoveAllItemsToLeft As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' btnRestore control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnRestore As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' TargetGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TargetGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' TargetDS control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected TargetDS As Global.System.Web.UI.WebControls.AccessDataSource
	End Class
End Namespace
